version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa-chat-app
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action_server:
    image: rasa/rasa-sdk:3.2.1
    build: actions/Dockerfile
    expose: 5055