version: '3.0'
services:
  rasa-flask:
    image: rasa-chatbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rasa-chat-app
    volumes: 
      - .:/rasa_app
    ports:
      - 5000:5000
    command: python3 app.py
    
  rasa-server:
    image: rasa/rasa:latest
    container_name: rasa-chatbot-server
    volumes: 
      - .:/app
    ports:
      - 5005:5005
    command: run -m models --enable-api --cors "*"

  action_server:
    container_name: "action_server"
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/actions
    ports:
      - 5055:5055


    
